version: "2.1"

services:
  app:
    image: kenayagi/odoo:12.0
    restart: always
    volumes:
      - odoodata:/var/lib/odoo
    networks:
      - traefik
      - net
    depends_on:
      db:
        condition: service_healthy
    environment:
      - TZ=Europe/Rome
      - POSTGRES_USER=odoo
    labels:
      - traefik.enable=true
      - traefik.f.port=8069
      - traefik.f.frontend.redirect.entryPoint=https
      - traefik.m.port=8069
      - traefik.m.frontend.redirect.entryPoint=https
      - traefik.p.port=8072
      - traefik.p.frontend.redirect.entryPoint=https

  db:
    image: postgres:11.6
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - net
    environment:
      - TZ=Europe/Rome
      - POSTGRES_USER=odoo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$ODOO_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  # Storage for Odoo data (filestore, etc.)
  odoodata:
  # Storage for PostgreSQL database
  pgdata:

networks:
  net:
  traefik:
    external: true
    name: traefik