name: Publish Docker image

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: set up docker buildx
        uses: docker/setup-buildx-action@v3
      - name: login to the docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # 5. Estrae i metadati (tag, label) per Docker
      # Questo passaggio prende il tag di GitHub (es. v1.2.3) e lo trasforma nel tag Docker
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/docker-odoo
          tags: |
            type=ref,event=tag
            type=raw,value=latest
      - name: build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          no-cache: true
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}